services:
  graphdb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: graphdb
    ports:
      - "${GRAPHDB_PORT}:7200"
    volumes:
      - ./graphdb:/opt/graphdb/home  # persist GraphDB data between restarts
      - ./_secret:/data  # .ttl ontology files
    environment:
      - GDB_JAVA_OPTS=-Xmx2g -Xms2g
      - REPO_ID=ontobot
    restart: unless-stopped