# Global environment variables are automatically loaded from .env file
include:
  - ./neo4j/docker-compose.yml
  - ./graphdb-sparql/docker-compose.yml
  - ./openwebui/docker-compose.yml
  # - ./openwebui-pipelines/docker-compose.yml
  - ./traefik/docker-compose.yml
