services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "${OPENWEBUI_PORT}:8080"
    environment:
      WEBUI_AUTH: "False"  # allows you to skip auth stuff, only for dev, once loaded can not be changed
      OLLAMA_BASE_URL: "https://genai-01.uni-hildesheim.de/ollama" # our uni ollama, can use other
    volumes:
      - ./open-webui:/app/backend/data